openapi: 3.2.0
info:
  title: Checkly Public Client certificates API
  version: v1
  description: These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
servers:
- url: https://api.checklyhq.com
security:
- Bearer: []
tags:
- name: Client certificates
paths:
  /v1/client-certificates:
    get:
      summary: Lists all client certificates.
      operationId: getV1Clientcertificates
      parameters:
      - name: x-checkly-account
        in: header
        schema:
          type: string
          description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
          x-format:
            guid: true
        description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
      tags:
      - Client certificates
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientCertificateList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsError'
    post:
      summary: Creates a new client certificate.
      operationId: postV1Clientcertificates
      parameters:
      - name: x-checkly-account
        in: header
        schema:
          type: string
          description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
          x-format:
            guid: true
        description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
      tags:
      - Client certificates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientCertificateCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientCertificateRetrieve'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsError'
  /v1/client-certificates/{id}:
    delete:
      summary: Deletes a client certificate.
      operationId: deleteV1ClientcertificatesId
      description: Permanently removes a client certificate.
      parameters:
      - name: x-checkly-account
        in: header
        schema:
          type: string
          description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
          x-format:
            guid: true
        description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
      - name: id
        in: path
        schema:
          type: string
          x-format:
            guid: true
        required: true
      tags:
      - Client certificates
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsError'
    get:
      summary: Shows one client certificate.
      operationId: getV1ClientcertificatesId
      parameters:
      - name: x-checkly-account
        in: header
        schema:
          type: string
          description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
          x-format:
            guid: true
        description: Your Checkly account ID, you can find it at https://app.checklyhq.com/settings/account/general
      - name: id
        in: path
        schema:
          type: string
          x-format:
            guid: true
        required: true
      tags:
      - Client certificates
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientCertificateRetrieve'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsError'
components:
  schemas:
    attributes:
      type: object
    error:
      type: string
      enum:
      - Unauthorized
    ClientCertificateCreate:
      type: object
      properties:
        host:
          type: string
          description: The host domain for the certificate without https://. You can use wildcards to match domains, e.g. "*.acme.com"
          example: www.acme.com
        cert:
          type: string
          description: The client certificate in PEM format as a string. This string should retain any line breaks, e.g. it should start similar to this "-----BEGIN CERTIFICATE-----\nMIIEnTCCAoWgAwIBAgIJAL+WugL...
        ca:
          type:
          - string
          - 'null'
          description: An optional CA certificate in PEM format as a string.
        key:
          type: string
          description: The private key in PEM format as a string.
        passphrase:
          type:
          - string
          - 'null'
          description: An optional passphrase for the private key. Your passphrase is stored encrypted at rest.
      required:
      - host
      - cert
    ForbiddenError:
      type: object
      properties:
        statusCode:
          type: number
          enum:
          - 403
        error:
          $ref: '#/components/schemas/Model1'
        message:
          type: string
          example: Forbidden
      required:
      - statusCode
      - error
    TooManyRequestsError:
      type: object
      properties:
        statusCode:
          type: number
          enum:
          - 429
        error:
          $ref: '#/components/schemas/Model2'
        message:
          type: string
          example: Too Many Requests
        attributes:
          $ref: '#/components/schemas/attributes'
      required:
      - statusCode
      - error
    Model1:
      type: string
      enum:
      - Forbidden
    Model2:
      type: string
      enum:
      - Too Many Requests
    UnauthorizedError:
      type: object
      properties:
        statusCode:
          type: number
          enum:
          - 401
        error:
          $ref: '#/components/schemas/error'
        message:
          type: string
          example: Bad Token
        attributes:
          $ref: '#/components/schemas/attributes'
      required:
      - statusCode
      - error
    ClientCertificateRetrieve:
      type: object
      properties:
        host:
          type: string
          description: The host domain for the certificate without https://. You can use wildcards to match domains, e.g. "*.acme.com"
          example: www.acme.com
        cert:
          type: string
          description: The client certificate in PEM format as a string. This string should retain any line breaks, e.g. it should start similar to this "-----BEGIN CERTIFICATE-----\nMIIEnTCCAoWgAwIBAgIJAL+WugL...
        ca:
          type:
          - string
          - 'null'
          description: An optional CA certificate in PEM format as a string.
        id:
          type: string
          x-format:
            guid: true
        created_at:
          type: string
          format: date-time
      required:
      - host
      - cert
      - id
    ClientCertificateList:
      type: array
      items:
        $ref: '#/components/schemas/ClientCertificateRetrieve'
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: Bearer
      description: 'The Checkly Public API uses API keys to authenticate requests. You can get the API Key <a href="https://app.checklyhq.com/settings/user/api-keys" target="_blank">here</a>.</br>Your API key is like a password: <br>keep it secure!</br></br>Authentication to the API is performed using the Bearer auth method in the Authorization header and using the account ID.</br></br>For example, set <b>Authorization</b> header while using cURL: <code>curl -H "Authorization: Bearer [apiKey]" "X-Checkly-Account: [accountId]"</code></br>'
